# Generated by Django 2.2.12 on 2021-02-20 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ascapost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField(default='AscaTitre', max_length=400)),
                ('image', models.ImageField(default='pic_folder/imagevide.jpg', upload_to='imageBDPost/')),
                ('description_courte', models.TextField(default='AscaDescription_courte', max_length=280)),
                ('description_longue', models.TextField(default='AscaDescription_longue')),
                ('auteur', models.TextField(default='auteur')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(max_length=280)),
                ('date', models.DateField(auto_now=True)),
                ('article_cible', models.ForeignKey(default='Ascapost', on_delete=django.db.models.deletion.CASCADE, to='monActivite.Ascapost')),
                ('ascanien', models.ForeignKey(default='Anonyme', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
