# Generated by Django 2.2.12 on 2021-02-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monActivite', '0002_auto_20210220_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascapost',
            name='image',
            field=models.ImageField(default='imageBDPost/imagevide.png', upload_to='imageBDPost/'),
        ),
    ]
