# Generated by Django 2.2.12 on 2021-02-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monActivite', '0003_auto_20210220_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascapost',
            name='image',
            field=models.ImageField(default='imageBDPost/imagevide.png', upload_to='../../../imageBDPost/'),
        ),
    ]
