# Generated by Django 2.2.12 on 2021-02-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='article',
        ),
    ]
